### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by agitator** [plone/plone.formwidget.recaptcha#16]
@cekk what is the state on https://github.com/plone/plone.formwidget.recaptcha/blob/python3_compatibility ?
Don't forget to update classifiers ;-)

**Comment by cekk** [comment]
I only started to fix the compatibility fixing imports.
The project stopped, so i didn't tried if it still works on python3.

You can use that branch as starting point

**Comment by jensens** [comment]
I added Py3 testing to TravisCI setup (allowed to fail for now) and rebased the branch with master.

**Comment by petschki** [comment]
@staeff what's the progress on py3 compat? I noticed the branch and your last changes. Maybe it's better to open a PR so that people better see the progress.

**Comment by petschki** [comment]
merged!
