### ISSUE TITLE
Use `requests` instead of `urllib` for HTTP requests 

### ISSUE THREAD

**Issue by staeff** [plone/plone.formwidget.recaptcha#21]
The package uses standardlibs `urllib` for HTTP request. (https://github.com/plone/plone.formwidget.recaptcha/blob/master/src/plone/formwidget/recaptcha/norecaptcha.py) To support Python 2 **and** 3 the imports have to be made through six.

`requests` (http://docs.python-requests.org/en/master/) makes HTTP requests easier and would not be needed to be imported through `six`. Is already used in other places in Plone and Add-Ons, so declaring it as dependency shouldn't do any harm.

**Comment by tisto** [comment]
@staeff I suppose this is fixed since we are on py3 already. Correct?

**Comment by staeff** [comment]
@tisto - it tried to do the replacement, but it was not as straightforward as I had hoped, so I went the `urllib` and `six` road in the https://github.com/plone/plone.formwidget.recaptcha/blob/master/src/plone/formwidget/recaptcha/norecaptcha.py.
